FROM debian:bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*

COPY server ./server
COPY employees.db ./employees.db

ENV PORT=8080
EXPOSE 8080

CMD ["./server"]

